# Generated by Django 6.0.7 on 2026-08-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_status_order_stripe_pid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='temporary@example.com', max_length=100),
            preserve_default=False,
        ),
    ]
