# Generated by Django 6.0.7 on 2026-08-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_homepageimage_homepagevideo_homepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepageimage',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_url',
        ),
        migrations.AddField(
            model_name='homepageimage',
            name='image',
            field=models.ImageField(default='default_image', upload_to='products/homepage/'),
        ),
        migrations.AddField(
            model_name='homepageimage',
            name='image_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default='default_image', upload_to='products/products/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='image_name',
            field=models.CharField(default='default_name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
