# Generated by Django 6.0.7 on 2026-08-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_homepageimage_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
