# Generated by Django 6.0.7 on 2026-08-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageimage',
            name='image',
            field=models.ImageField(default='default_image', upload_to='media/homepage/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='media/products/'),
        ),
    ]
