# Generated by Django 6.0.7 on 2026-08-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_homepageimage_image_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageimage',
            name='image',
            field=models.ImageField(default='default_image', upload_to='homepage/'),
        ),
    ]
