# Generated by Django 6.0.7 on 2026-08-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_href_homepage_bottom_left_button_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.video'),
        ),
    ]
