# Generated by Django 6.0.7 on 2026-08-20 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_video_product_product_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='video1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video1slot', to='products.video'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='video2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video2slot', to='products.video'),
        ),
    ]
