# Generated by Django 6.0.7 on 2026-08-20 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_homepage_video1_alter_homepage_video2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomepageVideo',
        ),
    ]
