# Generated by Django 6.0.7 on 2026-08-21 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_video_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='rating',
        ),
    ]
