# Generated by Django 6.0.7 on 2026-08-23 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_rating_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='link',
        ),
    ]
