# Generated by Django 6.0.7 on 2026-08-23 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_remove_product_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='character_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.href'),
        ),
        migrations.AlterField(
            model_name='href',
            name='url_name',
            field=models.URLField(max_length=225),
        ),
    ]
