# Generated by Django 6.0.7 on 2026-08-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_product_character_link_alter_href_url_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='comment',
            field=models.TextField(default='unknown'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rating',
            name='title',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
    ]
