# Generated by Django 6.0.7 on 2026-08-31 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_rating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='href',
            name='url_name',
            field=models.CharField(max_length=500),
        ),
    ]
